baseURL: 'https://kazuhidemimura.github.io/'

languageCode: en-us
title: "Kazuhide Mimura's page"
theme: "toha"
publishDir: "docs"


# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  jp:
    languageName: 日本語
    weight: 2

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: fr

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # background images
  background: "/images/DSC_1539.jpg"

  # The inverted logo will be used in the initial transparent navbar and
  # the main logo will be used in the non-transparent navbar.
  logo:
    main: images/logo_v2_inverted.png
    inverted: images/logo_v2_inverted.png
    favicon: images/logo_v2_inverted.png

  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/KazuhideMimura/KazuhideMimura.github.io
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true